import { DEFAULT_SYNTH, type SynthState } from "@/lib/audio/synth";

export interface SynthPreset {
  id: string;
  name: string;
  family: "Bass" | "Pluck" | "Pad" | "Lead" | "Stab";
  inspiration: string;
  description: string;
  hint: string;
  state: SynthState;
}

function preset(p: Partial<SynthState>): SynthState {
  return { ...DEFAULT_SYNTH, ...p };
}

export const SYNTH_PRESETS: SynthPreset[] = [
  {
    id: "anyma-bass",
    name: "Detuned Saw Bass",
    family: "Bass",
    inspiration: "Anyma · Massano",
    description:
      "Bajo sólido de melodic techno: dos saws desafinadas + sub, filtro grave con poca resonancia y envolvente corta.",
    hint: "Saw + Saw, detune ~10ct, sub al 60%, cutoff ~600 Hz, env del filtro corta y agresiva.",
    state: preset({
      osc1Type: "sawtooth",
      osc2Type: "sawtooth",
      osc2Detune: 11,
      osc2Mix: 0.6,
      subLevel: 0.6,
      filterCutoff: 600,
      filterRes: 3,
      ampAttack: 0.002,
      ampDecay: 0.4,
      ampSustain: 0.0,
      ampRelease: 0.15,
      filterEnvAmount: 0.65,
      filterDecay: 0.18,
      filterSustain: 0,
      drive: 0.25,
      reverbMix: 0.05,
      delayMix: 0,
      volume: -8,
    }),
  },
  {
    id: "mind-against-pluck",
    name: "Glassy Pluck",
    family: "Pluck",
    inspiration: "Mind Against · Innellea",
    description:
      "Pluck cristalino para arpegios. Square + triangle, decay rápido, mucho delay sincronizado y reverb largo.",
    hint: "Square + Triangle 5ª arriba, decay corto, sustain bajo, delay 3/8 con mix alto.",
    state: preset({
      osc1Type: "square",
      osc2Type: "triangle",
      osc2Detune: 700,
      osc2Mix: 0.4,
      subLevel: 0,
      filterCutoff: 3200,
      filterRes: 1.5,
      ampAttack: 0.003,
      ampDecay: 0.25,
      ampSustain: 0,
      ampRelease: 0.25,
      filterEnvAmount: 0.4,
      filterDecay: 0.2,
      filterSustain: 0,
      delayMix: 0.45,
      delayTime: 0.375,
      reverbMix: 0.5,
      drive: 0.05,
      volume: -12,
    }),
  },
  {
    id: "bodzin-pad",
    name: "Cinematic Pad",
    family: "Pad",
    inspiration: "Stephan Bodzin · Tale of Us",
    description:
      "Pad espacial de melodic techno. Saw + saw, ataque y release largos, mucha reverb, LFO suave en el filtro.",
    hint: "Attack 1.5s, release 2s, cutoff bajo con LFO al filtro depth medio, reverb 60%.",
    state: preset({
      osc1Type: "sawtooth",
      osc2Type: "sawtooth",
      osc2Detune: 9,
      osc2Mix: 0.7,
      subLevel: 0.2,
      filterCutoff: 1100,
      filterRes: 1.2,
      ampAttack: 1.5,
      ampDecay: 0.5,
      ampSustain: 0.85,
      ampRelease: 2.0,
      filterEnvAmount: 0.2,
      filterAttack: 0.8,
      filterDecay: 0.5,
      filterSustain: 0.5,
      filterRelease: 1.5,
      lfoRate: 0.4,
      lfoDepth: 0.3,
      lfoTarget: "filter",
      delayMix: 0.2,
      reverbMix: 0.6,
      drive: 0,
      volume: -14,
    }),
  },
  {
    id: "acid-lead",
    name: "Acid Lead",
    family: "Lead",
    inspiration: "Charlotte de Witte · Amelie Lens",
    description:
      "Lead 303-style. Una saw, sub, filtro con mucha resonancia y envelope al filtro al máximo.",
    hint: "Saw, mucha resonancia (Q≈12), env al filtro al 90%, decay corto, drive medio.",
    state: preset({
      osc1Type: "sawtooth",
      osc2Type: "sawtooth",
      osc2Mix: 0,
      subLevel: 0.5,
      filterCutoff: 350,
      filterRes: 12,
      ampAttack: 0.002,
      ampDecay: 0.2,
      ampSustain: 0.4,
      ampRelease: 0.1,
      filterEnvAmount: 0.9,
      filterDecay: 0.25,
      filterSustain: 0.1,
      delayMix: 0.18,
      reverbMix: 0.1,
      drive: 0.4,
      volume: -10,
    }),
  },
  {
    id: "minor-stab",
    name: "Minor Stab",
    family: "Stab",
    inspiration: "Tale of Us · Adriatique",
    description:
      "Stab corto y pegajoso para acordes menores. Square + saw, decay rápido, mucho ambiente.",
    hint: "Square + Saw, sin sustain, decay 200ms, delay 1/4, reverb medio.",
    state: preset({
      osc1Type: "square",
      osc2Type: "sawtooth",
      osc2Detune: -7,
      osc2Mix: 0.55,
      subLevel: 0.1,
      filterCutoff: 1800,
      filterRes: 2,
      ampAttack: 0.002,
      ampDecay: 0.18,
      ampSustain: 0,
      ampRelease: 0.3,
      filterEnvAmount: 0.35,
      filterDecay: 0.15,
      filterSustain: 0.1,
      delayMix: 0.3,
      delayTime: 0.5,
      reverbMix: 0.35,
      drive: 0.1,
      volume: -12,
    }),
  },
  {
    id: "innellea-arp",
    name: "Hypnotic Arp",
    family: "Pluck",
    inspiration: "Innellea · Massano",
    description:
      "Arp tipo melodic techno con LFO al filtro y delay 3/16. Hipnótico y constante.",
    hint: "Saw, LFO al filtro suave, delay 3/16, sustain bajo, decay medio.",
    state: preset({
      osc1Type: "sawtooth",
      osc2Type: "triangle",
      osc2Detune: 12,
      osc2Mix: 0.3,
      subLevel: 0,
      filterCutoff: 1600,
      filterRes: 4,
      ampAttack: 0.005,
      ampDecay: 0.3,
      ampSustain: 0.1,
      ampRelease: 0.2,
      filterEnvAmount: 0.3,
      filterDecay: 0.25,
      filterSustain: 0.05,
      lfoRate: 0.5,
      lfoDepth: 0.4,
      lfoTarget: "filter",
      delayMix: 0.35,
      delayTime: 0.28125,
      reverbMix: 0.3,
      drive: 0.1,
      volume: -12,
    }),
  },
];
